### PR TITLE
Move files from /scoped-properties to /settings to resolve deprecation warning.

### PR DESCRIPTION
**Pull request by smockle**

### CODE REVIEW

**Comment by rjocoleman** [comment]
thanks @smockle I don't have atom right now so I can't test this or cut a release. 

will do next week at the latest when my main computer is back from repair :hammer:

**Comment by smockle** [comment]
@rjocoleman Sounds good! Thanks for your work on this package!

**Comment by caleb531** [comment]
Hi,

Any update on the progress of this issue? The [removal of deprecated Atom APIs](http://blog.atom.io/2015/05/01/removing-deprecated-apis.html) is fast approaching.

Thanks,
Caleb

**Comment by rjocoleman** [comment]
v0.1.2 has been released - thanks again @smockle

**Pull request merged**
